/* Creacion de tabla GE */
CREATE USER ge IDENTIFIED BY ge;
GRANT CONNECT TO ge;
GRANT CREATE SESSION TO GE;
GRANT CREATE TABLE TO GE;
GRANT CREATE TABLESPACE TO GE;
GRANT CREATE VIEW TO GE;
GRANT CREATE ANY TRIGGER TO GE;
GRANT CREATE SEQUENCE TO GE;
GRANT UNLIMITED TABLESPACE TO GE;
GRANT SELECT ON sys.dual TO ge; /* Se le concede permiso a ge para dar select en dual, esto para la encriptación de contrase as */
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO ge; /* Se le concede permiso a ge para ejecutar en DBMS_CRYPTO, esto para la encriptación de contraseñas */
GRANT CREATE PROCEDURE TO ge;

/* Creacion de Usuario ADM (Administrador) */
CREATE USER ADM IDENTIFIED BY adm;
GRANT CONNECT TO adm;
GRANT CREATE SESSION TO ADM;
GRANT CREATE TABLE TO ADM;
GRANT CREATE TABLESPACE TO ADM;
GRANT CREATE VIEW TO ADM;
GRANT CREATE ANY TRIGGER TO ADM;
GRANT CREATE SEQUENCE TO ADM;
GRANT UNLIMITED TABLESPACE TO ADM;